install.packages("testthat")
install.packages("readxl")
install.packages("RSQLite")
install.packages("jsonlite")
install.packages("jpeg")
install.packages("imager")
install.packages("dplyr")
install.packages("ggplot2")